
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (41, 'es', '*', 'Todas', 'Todas', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (40, 'es', '*', 'Dados abertos de indicadores', 'Indicadores de datos abiertas', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (42, 'es', '*', 'Indicador', 'Indicador', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (43, 'es', '*', 'Todos', 'Todos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (44, 'es', '*', 'Formato', 'Formato', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (1, 'pt-br', '*', 'Cidades', 'Cidades', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (132, 'pt-br', '*', 'vezes', 'vezes', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (133, 'pt-br', '*', 'Descontados distritos cujo valor é zero', 'Descontados distritos cujo valor é zero', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (134, 'pt-br', '*', 'das subprefeituras', 'das subprefeituras', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (45, 'es', '*', 'CSV', 'CSV', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (27, 'es', '*', 'Cidades', 'Ciudades', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (28, 'es', '*', 'Indicadores', 'Indicadores', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (29, 'es', '*', 'Links', 'Links', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (30, 'es', '*', 'Contato', 'Contacto', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (31, 'es', '*', 'Brasil', 'Brasil', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (32, 'es', '*', 'Subprefeituras', 'Burgos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (33, 'es', '*', 'Indicadores separados por eixos', 'Indicadores separados ejes', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (46, 'es', '*', 'XLS', 'XLS', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (34, 'es', '*', 'Carregando...', 'Cargando...', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (35, 'es', '*', 'Mapa do Site', 'Mapa del sitio', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (36, 'es', '*', 'comparar com outras cidades', 'comparar con otras ciudades', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (38, 'es', '*', 'Por Indicador', 'Por Indicator', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (39, 'es', '*', 'Selecione um estado acima e clique sobre os pontos do mapa para visualizar os indicadores', 'Seleccione un estado anterior y haga clic en el mapa para ver los marcadores señala', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (47, 'es', '*', 'XML', 'XML', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (48, 'es', '*', 'JSON', 'JSON', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (49, 'es', '*', 'Arquivo de indicadores', 'Indicadores Archivo', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (50, 'es', '*', 'Efetuar download dos indicadores', 'Asegúrese de descargar indicadores', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (51, 'es', '*', 'Nome da cidade', 'Nombre de la ciudad', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (52, 'es', '*', 'Nome do indicador', 'Nombre del indicador', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (53, 'es', '*', 'Data', 'Fecha', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (54, 'es', '*', 'Valor', 'Valor', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (55, 'es', '*', 'ID da cidade', 'City ID', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (56, 'es', '*', 'Eixo', 'Eje', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (57, 'es', '*', 'ID Indicador', 'Indicador ID', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (58, 'es', '*', 'Formula do indicador', 'Indicador Fórmula', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (59, 'es', '*', 'Meta do indicador', 'Indicador Objetivo', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (60, 'es', '*', 'Fonte da meta do indicador', 'Fuente del indicador de objetivos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (61, 'es', '*', 'Tags do indicador', 'Indicador Etiquetas', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (62, 'es', '*', 'Faixa', 'Grupo', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (63, 'es', '*', 'Meta do valor', 'Valor objetivo', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (64, 'es', '*', 'Fontes', 'Fuentes', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (65, 'es', '*', 'Nome', 'Nombre', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (66, 'es', '*', 'ID', 'ID', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (67, 'es', '*', 'Tipo', 'Tipo', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (68, 'es', '*', 'Apelido', 'Nombre', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (69, 'es', '*', 'Fonte', 'Fuente', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (70, 'es', '*', 'Unidade de medida', 'Unidad de medida', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (71, 'es', '*', 'Fonte do valor', 'Fuente de valor', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (72, 'es', '*', 'Observações', 'Comentarios', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (73, 'es', '*', 'O arquivo de indicador contém as seguintes informações', 'El indicador de archivo contiene la siguiente información', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (74, 'es', '*', 'Descrição da meta do indicador', 'Descripción del indicador de destino', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (75, 'es', '*', 'Operação da meta do indicador', 'El funcionamiento del indicador de objetivos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (76, 'es', '*', 'Descrição do indicador', 'Descripción del indicador', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (77, 'es', '*', 'Observações do indicador', 'Observaciones del indicador', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (78, 'es', '*', 'Período do indicador', 'Indicador Período', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (79, 'es', '*', 'Justificativa do valor não preenchido', 'Valor Justificación vacantes', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (80, 'es', '*', 'Região', 'Región', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (81, 'es', '*', 'se existir', 'si hay', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (82, 'es', '*', 'Período de atualização', 'Período de actualización', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (83, 'es', '*', 'É Básica?', 'Es básico?', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (84, 'es', '*', 'Arquivo de variáveis', 'Variables de archivo', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (85, 'es', '*', 'Efetuar download das variáveis', 'Asegúrese de descarga de las variables', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (86, 'es', '*', 'O arquivo de variável contém as seguintes informações', 'El archivo de variable contiene la siguiente información', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (100, 'es', '*', 'Cidade', 'Ciudad', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (88, 'es', '*', 'Média', 'Promedio', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (89, 'es', '*', 'Classificação', 'Clasificación', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (90, 'es', '*', 'Distritos', 'Distritos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (91, 'es', '*', 'Alta / Melhor', 'Alto / Mejor', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (92, 'es', '*', 'Acima da média', 'Por encima del promedio', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (93, 'es', '*', 'Abaixo da média', 'Por debajo del promedio', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (94, 'es', '*', 'Baixa / Pior', 'Bajo ', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (95, 'es', '*', 'Média com base na soma dos números', 'Promedio sobre la base de la suma de los números', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (96, 'es', '*', 'dos distritos', 'del distritos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (98, 'es', '*', 'mapa', 'mapa', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (87, 'es', '*', 'Subprefeitura', 'Burgo', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (97, 'es', '*', 'tabela', 'tabla', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (99, 'es', '*', 'gráficos', 'gráficos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (101, 'es', '*', 'Desenvolvido por', 'Desarrollado por', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (103, 'es', '*', 'Download', 'Descargar', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (104, 'es', '*', 'Parceiros', 'Partners', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (37, 'es', '*', 'Dados abertos', 'Datos abiertos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (135, 'pt-br', '*', 'gráficos', 'gráficos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (2, 'pt-br', '*', 'Indicadores', 'Indicadores', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (3, 'pt-br', '*', 'Links', 'Links', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (5, 'pt-br', '*', 'Brasil', 'Brasil', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (6, 'pt-br', '*', 'tabela', 'tabela', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (7, 'pt-br', '*', 'mapa', 'mapa', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (8, 'pt-br', '*', 'Cidade', 'Cidade', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (9, 'pt-br', '*', 'Todas', 'Todas', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (10, 'pt-br', '*', 'Indicador', 'Indicador', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (11, 'pt-br', '*', 'Todos', 'Todos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (12, 'pt-br', '*', 'Formato', 'Formato', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (13, 'pt-br', '*', 'CSV', 'CSV', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (14, 'pt-br', '*', 'XLS', 'XLS', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (15, 'pt-br', '*', 'XML', 'XML', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (16, 'pt-br', '*', 'JSON', 'JSON', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (17, 'pt-br', '*', 'Data', 'Data', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (18, 'pt-br', '*', 'Valor', 'Valor', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (19, 'pt-br', '*', 'Eixo', 'Eixo', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (20, 'pt-br', '*', 'Faixa', 'Faixa', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (21, 'pt-br', '*', 'Fontes', 'Fontes', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (22, 'pt-br', '*', 'Nome', 'Nome', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (23, 'pt-br', '*', 'ID', 'ID', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (24, 'pt-br', '*', 'Tipo', 'Tipo', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (25, 'pt-br', '*', 'Apelido', 'Apelido', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (26, 'pt-br', '*', 'Fonte', 'Fonte', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (4, 'pt-br', '*', 'Contato', 'Contato', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (105, 'pt-br', '*', 'Por Indicador', 'Por Indicador', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (106, 'pt-br', '*', 'Carregando...', 'Carregando...', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (107, 'pt-br', '*', 'Dados abertos', 'Dados abertos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (108, 'pt-br', '*', 'Selecione um estado acima e clique sobre os pontos do mapa para visualizar os indicadores', 'Selecione um estado acima e clique sobre os pontos do mapa para visualizar os indicadores', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (109, 'pt-br', '*', 'Mapa do Site', 'Mapa do Site', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (110, 'pt-br', '*', 'Desenvolvido por', 'Desenvolvido por', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (111, 'pt-br', '*', 'Download', 'Download', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (112, 'pt-br', '*', 'Parceiros', 'Parceiros', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (113, 'pt-br', '*', 'Indicadores separados por eixos', 'Indicadores separados por eixos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (114, 'pt-br', '*', 'Subprefeituras', 'Subprefeituras', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (115, 'pt-br', '*', 'comparar com outras cidades', 'comparar com outras cidades', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (116, 'pt-br', '*', 'Subprefeitura', 'Subprefeitura', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (117, 'pt-br', '*', 'Alta / Melhor', 'Alta / Melhor', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (118, 'pt-br', '*', 'Acima da média', 'Acima da média', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (119, 'pt-br', '*', 'Média', 'Média', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (120, 'pt-br', '*', 'Abaixo da média', 'Abaixo da média', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (121, 'pt-br', '*', 'Baixa / Pior', 'Baixa / Pior', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (122, 'pt-br', '*', 'Média com base na soma dos números', 'Média com base na soma dos números', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (123, 'pt-br', '*', 'dos distritos', 'dos distritos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (124, 'pt-br', '*', 'Classificação', 'Classificação', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (125, 'pt-br', '*', 'Distrito', 'Distrito', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (126, 'pt-br', '*', 'Distritos', 'Distritos', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (127, 'pt-br', '*', 'Fator de desigualdade', 'Fator de desigualdade', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (128, 'pt-br', '*', 'Período', 'Período', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (129, 'pt-br', '*', 'Máximo', 'Máximo', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (130, 'pt-br', '*', 'Mínimo', 'Mínimo', NULL);
INSERT INTO lexicon (id, lang, lex, lex_key, lex_value, notes) VALUES (131, 'pt-br', '*', 'Desigualdade', 'Desigualdade', NULL);



SELECT pg_catalog.setval('lexicon_id_seq', 135, true);

