package RNSP::PCS::Model::RNSP::PCS;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'RNSP::PCS::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=rnsp_pcs;host=localhost',
        user => 'postgres',
        password => 'system',
        quote_names => q{1},
    }
);

=head1 NAME

RNSP::PCS::Model::RNSP::PCS - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<RNSP::PCS>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<RNSP::PCS::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

renato

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
